---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: 1. Install wget and httpd
      yum:
        name:
          - wget
          - java-1.8.0-openjdk
          - libselinux-python
        state: present

    - name: 2.Copy Tomcat Service from local to remote
      copy:
        src: jdk-8u211-linux-x64.tar.gz
        dest: /opt/
        mode: 0755

    - name: 3.Create /opt/tomcat directory
      file:
        path: /opt/java
        state: directory
        mode: 0755
    - name: 3. download and unarchive
      unarchive:
        src: /opt/jdk-8u211-linux-x64.tar.gz
        dest: /opt/java
        extra_opts: [--strip-components=1]

    - name: 4.Download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: 5.Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: 6.Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout
