
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "JenkinsServer"
  config.vm.network "private_network", ip: "192.168.50.10"

	config.vm.provider "virtualbox" do |v|
    v.name = "JenkinsServer"
    v.memory = 1024
    v.cpus = 2
	end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
