Vagrant.configure("2") do |config|
  config.vm.box = "genebean/centos-7-docker-ce"
  config.vm.box_version = "2.1.0"
  config.vm.hostname = "Docker"
  config.vm.network "private_network", ip: "192.168.50.50"

  config.vm.provider "virtualbox" do |v|
    v.name = "Docker"
    v.memory = 1024
    v.cpus = 2
  end
end
